version: 1.0.{build}

image: Visual Studio 2017

clone_folder: c:\projects\pdfium\src

init:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%\..\..

    appveyor DownloadFile https://storage.googleapis.com/chrome-infra/depot_tools.zip

    7z -bd x depot_tools.zip -odepot_tools

    set DEPOT_TOOLS_WIN_TOOLCHAIN=0

    depot_tools\update_depot_tools

    cd %APPVEYOR_BUILD_FOLDER%

environment:
  matrix:
  - IS_DEBUG: true
    ARCHITECTURE: x86
  - IS_DEBUG: true
    ARCHITECTURE: x64
  - IS_DEBUG: false
    ARCHITECTURE: x86
  - IS_DEBUG: false
    ARCHITECTURE: x64

install:
- cmd: >-
    set DEPOT_TOOLS_WIN_TOOLCHAIN=0

    PATH C:\projects\depot_tools;%PATH%

    cd %APPVEYOR_BUILD_FOLDER%

    gclient config https://%APPVEYOR_REPO_PROVIDER%.com/%APPVEYOR_REPO_NAME% --unmanaged

    gclient sync --no-history --shallow

build_script:
- cmd: >-
    set DEPOT_TOOLS_WIN_TOOLCHAIN=0

    cd %APPVEYOR_BUILD_FOLDER%\pdfium

    gn gen --args="pdf_enable_v8=false pdf_enable_xfa=false pdf_use_skia=false pdf_is_complete_lib=true is_component_build=false use_lld=false use_sysroot=false is_clang = false is_debug=%IS_DEBUG% target_cpu=\"%ARCHITECTURE%\"" out/release

    cd out/release

    ninja -v pdfium

    tree /F

    7z a pdfium-headers.zip %APPVEYOR_BUILD_FOLDER%\pdfium\public

test: off

artifacts:
- path: '**\pdfium.*'

